<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK2hm5Ql\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK2hm5Ql/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK2hm5Ql.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK2hm5Ql\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK2hm5Ql\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K2hm5Ql',
    'container.build_id' => '0f6550b2',
    'container.build_time' => 1569225077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK2hm5Ql');
