<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhv2fPP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhv2fPP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhv2fPP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhv2fPP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEf3le5y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ef3le5y',
    'container.build_id' => '659c21fa',
    'container.build_time' => 1569226671,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEf3le5y');
