<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSx888zv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSx888zv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSx888zv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSx888zv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSx888zv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Sx888zv',
    'container.build_id' => '22e8882b',
    'container.build_time' => 1569227786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSx888zv');
